name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
        - completed
    
        
jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Pull Docker Image
        run: sudo docker pull fauverick/deranger-cicd:latest
      -
        name: Delete Old Docker Container
        run: sudo docker rm -f deranger-cicd-container || true
      -
        name: Run Docker Container
        run: sudo docker run -d -p 4000:4000 --name deranger-cicd-container fauverick/deranger-cicd:latest 