name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get Code
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        env:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      -
        name: Build Docker Image
        run: docker build -t deranger-cicd .
      -
        name: Push to Docker Hub
        run: docker push fauverick/deranger-cicd:latest